### PR TITLE
Modernize pas.plugins.oidc

### LINKED ISSUE #32: Use plone/meta
# Tasks

- [ ] Implement plone/meta
- [ ] Package documentation in Markdown instead of ReST

### LINKED ISSUE #33: Drop support for Plone 5.2
# Tasks

- [ ] Drop support for Python 2.7 (conditional imports, encoding declaration, usage of object)
- [ ] Drop support for Plone 5.2

### LINKED ISSUE #34: Move tests to pytest
# Tasks

- [ ] Rewrite tests from unittest to pytest with [pytest-plone](https://pypi.org/project/pytest-plone/)

### LINKED ISSUE #35: Allow dict instances to hold userinfo

### PR DESCRIPTION
**Pull request by ericof**
# Issues
- Fixes #32
- Fixes #33
- Fixes #34
- Fixes #35

### CODE REVIEW

**Comment by ericof** [comment]
I would suggest to release this as 1.0b1, and tell people to pin to 1.0a6 if they are using it with Plone 5.2

**Review by mamico — APPROVED** [review]
That's awesome!

**Comment by erral** [comment]
> I would suggest to release this as 1.0b1, and tell people to pin to 1.0a6 if they are using it with Plone 5.2

I would suggest to release 1.0a6 as 1.0 with Plone 5.2 support and a 2.0 with Plone 6-only.

**Comment by ericof** [comment]
@erral, I agree with this approach. 
@mamico, could you please make a 1.0.0 release?

**Comment by mauritsvanrees** [comment]
Just as a quick note: both 1.0.0 and 2.0.0a1 seem to work fine in our test environment for one customer.

**Pull request merged**
