### PR TITLE
Implement Keycloak Group Enumeration and Group Introspection

### LINKED ISSUE #42: Implement Group Enumeration

### PR DESCRIPTION
**Pull request by ericof**
Fixes #42

### CODE REVIEW

**Comment by erral** [comment]
I am not sure whether this plugin is the place to implement the specifics for Keycloak group enumeration or pas.plugins.keycloakgroupenumeration would be a better place.

**Comment by ericof** [comment]
@erral Let me check how feasible it is to extract just the group support to a new package, meanwhile @mpeeters I wait for your feedback ;-)

**Comment by mpeeters** [comment]
@ericof I tried the new changes and I still have the same issue, my user have the groups and roles (listed in the Plone control panel), but those roles are not effective, and thus, my user does not have any related permissions (checked with manage_access)

Regarding performance, it is way better than before.

**Comment by ericof** [comment]
Interesting 🤔, I will double check what could be the issue with the roles not being applied

**Comment by ericof** [comment]
@erral, @mpeeters: Please take a look at the updated version -- that only mentions [pas.plugins.keycloakgroups](https://pypi.org/project/pas.plugins.keycloakgroups/)

**Review by mamico — APPROVED** [review]
Agreed about moving the functionality to a separate product.

**Pull request merged**
