### PR TITLE
Add note about Varnish and cookie-pass to the readme.

### LINKED ISSUE #11: came_from does not work because cookies are not set
In case you don't mind much that came_from does not work, note that I think that the same is true for the other parameters that are set in the session: state, nonce, optionally verifier. The plugin works, so maybe these are all just optional for extra security, and are ignored when they are not there. A guess.

Anyway, with the standard Plone login form, a came_from parameter works. Visit this and after login you end up on the news page:

http://localhost:8080/Plone/login?came_from=http://localhost:8080/Plone/news

Using the oidc login form, this does not work, you end up on the homepage instead:

http://localhost:8080/Plone/acl_users/oidc/login?came_from=http://localhost:8080/Plone/news

The plugin does try to pass the came_from, everything seems to be correct. It saves it in the session, either via cookies or a "proper" session. After login has worked, it reads it from the session and redirects there.

Note that if you set `use_session_data_manager` to True in the plugin, because you use sessions in for example memcache, then Plone still needs to set a cookie once with the key to the session data.

I first thought the problem was that on the response we add a `Set-Cookie` header and then we redirect to the OIDC server. The cookie is for the Plone domain, not the OIDC domain (assuming this is different), so the browser ignores it. It could be that this is part of the problem, but the problem is deeper.

Apparently, when you add a `Set-Cookie` header on a redirect request, no cookie will be set by the browser. That is what I see on my Mac on Safari and Chrome.

Or maybe Zope/Plone removes this header when it does a redirect? No, with `curl` I *do* see a Set-Cookie header.

Stackoverflow describes the [same problem](https://stackoverflow.com/questions/57026956/on-safari-cookies-are-not-saved-when-sent-with-redirect#57119113). This question is about Safari/webkit, and the answer points to a [webkit issue](https://bugs.webkit.org/show_bug.cgi?id=3512). But it seems that more browsers share this behavior.  And the webkit issue suggests it is an HTTP protocol problem, if I interpret it correctly.

Another answer on the same stackoverflow question suggests to not use a redirect, but return a status 200 with an html page that does a [javascript redirect](https://stackoverflow.com/a/70295152/621201). A bit ugly, but that may do the trick.

Do other users of this plugin see the same?

### PR DESCRIPTION
**Pull request by mauritsvanrees**
Fixes https://github.com/collective/pas.plugins.oidc/issues/11

### CODE REVIEW

**Comment by erral** [comment]
@mauritsvanrees we can even add this to the default configuration of plone.recipe.varnish right? It will not harm right?

**Comment by mauritsvanrees** [comment]
> @mauritsvanrees we can even add this to the default configuration of plone.recipe.varnish right? It will not harm right?

I think that would (very slightly) drop performance for every user of this recipe, and only benefit the users of this plugin, as it is the only package that uses a cookie `__ac_session`.

But if we could change the recipe to treat any cookie starting with `__ac` this way, that may be good.

**Comment by mamico** [comment]
@mauritsvanrees @fredvd good catch! `__ac_session` is used also for state and should be checked against OAuth2 response (see https://github.com/collective/pas.plugins.oidc/blob/main/src/pas/plugins/oidc/browser/view.py#L190). I suppose that for a problem similar like this, the check was actually commented.

Alternatively, any suggestions for handling session information differently/better?

**Review by mamico — APPROVED** [review]

**Comment by fredvd** [comment]
Anything 'better' around the cookie handling could maybe be to manage the cookie setting client side using javascript and not depending on server side cookies.  I've seen this also with consent state: you can do this 'server side' with forms that submit to the server and the server setting the state, or do everything client side.  Drawback: graceful degradation. But I have no clue if this is feasible with the OIDC step and if it would bring any advantage. 

Concerning cookie parsing in Varnish: there's some complex code now in the plone.recipe.varnish recipe that does the cookie sanitizing and it might impact performance with more cookie exceptions, but we haven't noticed anything special with 5-6 extra cookies in the whitelist.    https://github.com/collective/plone.recipe.varnish/blob/266195e1c46d23af120a5f69dcad16dc8204635a/plone/recipe/varnish/templates/varnish6.vcl.jinja2#L145-L171

If performance would become a problem, the Varnish developers & community maintain a library of curate vmod's, varnish-modules: https://github.com/varnish/varnish-modules .   The plone.recipe.varnish recipe can install those and the varnish-modules for 6.0 still  have the cookie module  (if you look at the master branch the cookie module is no longer there because it became part of the core varnish distribution in 6.4)  We could decide to make the recipe dependent on varnish-modules and use the cookie vmod to do the cleaning/parsing. 

But that's more for a discussion on the p.r.varnish repo and maybe the effort for that is better spend on upgrading the buildout recipe to use the latest Varnish 7.X.   It does not seem that Varnish Software is going to release a new LTS version again soon, despite their 'promise' when switching to a half yearly time boxed release schedule.  Not their priority in the current business model with Varnish Plus and apparently enough customers.

**Comment by mauritsvanrees** [comment]
> @mauritsvanrees @fredvd good catch! `__ac_session` is used also for state and should be checked against OAuth2 response (see https://github.com/collective/pas.plugins.oidc/blob/main/src/pas/plugins/oidc/browser/view.py#L190). I suppose that for a problem similar like this, the check was actually commented.

Quick point: the commented line uses an assert statement, and this will be optimised away by the compiler, at least when compiling it to a `.pyo` file. So it would be better to use a condition and raise a ValueError (or similar) when the condition fails.

> Alternatively, any suggestions for handling session information differently/better?

It seems fine and logical. You need some way to compare information from the browser, the oidc server, and Plone. Cookies seem fine for that.
No immediate idea on an alternative.

Well, we could use standard Zope sessions. IIRC they use the `ZopeId` cookie to store a session id, and this is already in the `cookie-whitelist` of the recipe, so that should work. But then you need proper versions and configuration of `tempstorage` and related products that Plone 6 does not use by default anymore. Or add [`Products.mcdutils`](https://mcdutils.readthedocs.io/en/latest/) as [the code points out](https://github.com/collective/pas.plugins.oidc/blob/1.0a4/src/pas/plugins/oidc/browser/view.py#L22-L23), and store the sessions in a shared memcache server. So not something that really works out of the box. The current way, with all information stored in a cookie without server side sessions, should preferably always be available as fallback.

**Pull request merged**
